name: Build and Deploy to FTP

on:
    push:
        branches:
            - main # Trigger on push to main branch

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout Repository
            - name: Checkout Repository
              uses: actions/checkout@v2

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            # Step 3: Install Dependencies
            - name: Install Dependencies
              working-directory: ./front
              run: npm install

            # Step 4: Build Project
            - name: Build Frontend
              working-directory: ./front
              run: npm run build
              env:
                  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

            # Step 5: Create .env file for backend
            - name: Create .env file for backend
              run: |
                  echo "DB_HOST=${{ secrets.DB_HOST }}" > ./back_php/.env
                  echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./back_php/.env
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./back_php/.env
                  echo "DB_USER=${{ secrets.DB_USER }}" >> ./back_php/.env
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./back_php/.env

            # Step 6: Deploy frontend
            - name: Upload Frontend Static
              uses: BaptLab/FTP-Deploy-Action@fix-550-skip
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./front/out/
                  server-dir: ./www/chess_puzzle_maker/
                  dangerous-clean-slate: false

            # Step 7: Deploy backend PHP
            - name: Upload Backend PHP
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./back_php/
                  server-dir: ./www/chess_puzzle_maker/back_php/
