name: Build and Deploy to FTP

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install Dependencies
              working-directory: ./front
              run: npm install

            - name: Build Frontend (Static Export via next.config.js)
              working-directory: ./front
              run: npm run build

            - name: Upload Static Site to FTP (Frontend only)
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./front/out/
                  server-dir: ./www/chess_puzzle_maker/
