name: Build and Deploy to FTP

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              working-directory: ./front
              run: npm ci

            - name: Build frontend (static export → front/out)
              working-directory: ./front
              run: npm run build # output: "export" = dossier /out

            # ───────────── 1) Upload du site statique ─────────────
            - name: Upload static site
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./front/out/ # ⬅️ uniquement le contenu exporté
                  server-dir: ./www/chess_puzzle_maker/ # ⬅️ racine publique
                  dangerous-clean-slate: true # nettoie ce répertoire AVANT upload

            # ───────────── 2) Upload du backend PHP ─────────────
            - name: Upload backend PHP
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./back_php/ # ⬅️ seulement le back
                  server-dir: ./www/chess_puzzle_maker/back_php/
                  dangerous-clean-slate: true # nettoie le dossier back_php/ avant upload
