name: Build and Deploy to FTP

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: Install dependencies
              working-directory: ./front
              run: npm ci

            - name: Build frontend (static export)
              working-directory: ./front
              run: npm run build

            - name: Upload front/out + back_php to FTP
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local-dir: ./ # Racine du repo
                  server-dir: ./www/chess_puzzle_maker/
                  dangerous-clean-slate: true # 🔥 Nettoie tout avant d’uploader
                  exclude: |
                      **                         # Tout exclu par défaut
                  include: |
                      front/out/**               # Inclut uniquement le front exporté
                      back_php/**                # Et ton backend PHP
